name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: check the code
      run: |
        ls -l && pwd 
        ls -la /home/runner/work/DVReflectors/DVReflectors
    - name: Build the Docker image
      run: |
        docker build . --file DVReflectors/YSFReflector/Dockerfile --tag shaposhnikoff/ysfreflector:$(date +%s)
