name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  YSFReflector:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE/YSFReflector/docker && 
        docker build . --tag shaposhnikoff/ysfreflector:$(date +%s)
  NXDNReflector:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE/NXDNReflector/docker && 
        docker build . --tag shaposhnikoff/nxdnreflector:$(date +%s)
  P25Reflector:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE/NXDNReflector/docker && 
        docker build . --tag shaposhnikoff/p25reflector:$(date +%s)
        
