name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: check the code
      run: |
        ls -l && pwd 
        echo $GITHUB_WORKSPACE/YSFReflector
 
    - name: Build the Docker image
      run: |
        docker build . --file $GITHUB_WORKSPACE/YSFReflector/Dockerfile --tag shaposhnikoff/ysfreflector:$(date +%s)
